services:
  airvpn:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./web/data:/app/data
    env_file:
      - .env
    restart: unless-stopped

